### ISSUE TITLE
linuxbrew prefixes `ytui-tap` with `homebrew-`

### ISSUE THREAD

**Issue by zaz** [Banh-Canh/ytui-tap#1]
<details>
<summary>With a fresh install of brew on Fedora 40:</summary>

```
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
$ echo >> /home/user/.bashrc
$ echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/user/.bashrc
$ eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
```

</details>

```
$ brew install banh-canh/ytui-tap/formula
==> Tapping banh-canh/ytui-tap
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/banh-canh/homebrew-ytui-tap'...
Username for 'https://github.com':
Password for 'https://github.com':
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/banh-canh/homebrew-ytui-tap/'
Error: Failure while executing; `git clone https://github.com/banh-canh/homebrew-ytui-tap /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/banh-canh/homebrew-ytui-tap --origin=origin --template= --config core.fsmonitor=false` exited with 128.
```

It seems homebrew prefixes the repo with `homebrew-`.  So if you renamed this `homebrew-ytui` and changed the instructions to `brew install banh-canh/ytui/formula`, I believe it would work fine.  It's asking for authentication because homebrew-ytui-tap yields a 404 error.

**Comment by Banh-Canh** [comment]
i'll take a look, didn't really test it because i don't have an environnment that actually require using brew, i'll let you know

**Comment by Banh-Canh** [comment]
it indeed required this non-optional prefixes, i attempted to fix it. If you could try and report i would be grateful :)

**Comment by zaz** [comment]
Thanks a lot! This works very smoothly with [some tweaks to the installation instructions](https://github.com/Banh-Canh/ytui/pull/59).
